//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BirthdayBuddyFW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuddyInfo
    {
        public string NAME { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public string BUDDYNAME { get; set; }
        public int ID { get; set; }
    }
}
